.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. globalbitcoin_qt test_globalbitcoin_qt
clean: FORCE
	$(MAKE) -C .. globalbitcoin_qt_clean test_globalbitcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_globalbitcoin_qt_check
globalbitcoin-qt globalbitcoin-qt.exe: FORCE
	 $(MAKE) -C .. globalbitcoin_qt
